---
abstract: 'Multi host ssh executer'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MultiSsh
provides:
  App::MultiSsh:
    file: lib/App/MultiSsh.pm
    version: 0.01
requires:
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App::MultiSsh
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/App-MultiSsh.git
version: 0.01
